---
swagger: "2.0"
info:
  description:
    This is the API of the Todoz app, This part of the project will have
    full responsibility for the functionality of the apps.
  version: 1.0.0
  title: Todoz API
  contact:
    email: mohammadraufzahed@protonmail.com
host: localhost:8080
basePath: "/api"
tags:
  - name: register
    description: Register Endpoint
  - name: user
    description: User Management Endpoint
schemes:
  - https
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths: !!import/payload
  paths:
    - routes/register.yaml
    - routes/user.yaml
